// <auto-generated />
using System;
using HousingInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HousingInfrastructure.Migrations
{
    [DbContext(typeof(HousingContext))]
    partial class HousingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HousingDomain.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("HousingId")
                        .HasColumnType("integer")
                        .HasColumnName("housing_id");

                    b.HasKey("Id")
                        .HasName("Availability_pkey");

                    b.HasIndex("HousingId");

                    b.ToTable("Availability", (string)null);
                });

            modelBuilder.Entity("HousingDomain.Models.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("HousingId")
                        .HasColumnType("integer")
                        .HasColumnName("housing_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("BookingRequests_pkey");

                    b.HasIndex("HousingId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("HousingDomain.Models.Housing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("address");

                    b.Property<decimal?>("Area")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Rooms")
                        .HasColumnType("integer")
                        .HasColumnName("rooms");

                    b.HasKey("Id")
                        .HasName("housing_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("housing", (string)null);
                });

            modelBuilder.Entity("HousingDomain.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CleanLevel")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("Clean_level");

                    b.Property<string>("Guests")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("NoiseLevel")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("Noise_level");

                    b.Property<bool>("Pets")
                        .HasColumnType("boolean");

                    b.Property<string>("SleepMode")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("Sleep_mode");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("Profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "unique_user_profile")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("HousingDomain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("HousingId")
                        .HasColumnType("integer")
                        .HasColumnName("housing_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex("HousingId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("HousingDomain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HousingDomain.Models.Availability", b =>
                {
                    b.HasOne("HousingDomain.Models.Housing", "Housing")
                        .WithMany("Availabilities")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_housing");

                    b.Navigation("Housing");
                });

            modelBuilder.Entity("HousingDomain.Models.BookingRequest", b =>
                {
                    b.HasOne("HousingDomain.Models.Housing", "Housing")
                        .WithMany("BookingRequests")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_housing");

                    b.HasOne("HousingDomain.Models.User", "User")
                        .WithMany("BookingRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_user");

                    b.Navigation("Housing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingDomain.Models.Housing", b =>
                {
                    b.HasOne("HousingDomain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HousingDomain.Models.Profile", b =>
                {
                    b.HasOne("HousingDomain.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HousingDomain.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingDomain.Models.Review", b =>
                {
                    b.HasOne("HousingDomain.Models.Housing", "Housing")
                        .WithMany("Reviews")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_housing");

                    b.HasOne("HousingDomain.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_user");

                    b.Navigation("Housing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingDomain.Models.Housing", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("BookingRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HousingDomain.Models.User", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("Profile");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
